---
deployment:
  tasks:
    - export DEPLOYPATH=/home/azzagenciaazz/leadhub_crm
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH && npm install
    - cd $DEPLOYPATH && npx prisma generate
    - cd $DEPLOYPATH && export DATABASE_URL="mysql://azzagenciaazz_4dm_leadhub:cakbiz-Netcin-wiqti8@localhost:3306/azzagenciaazz_leadhub_crm" && npx prisma db push --accept-data-loss
    - cd $DEPLOYPATH && export NEXT_PUBLIC_BASE_URL="https://app.azzagencia.com.br" && npm run build
